### ISSUE TITLE
about the requirements.txt file

### ISSUE THREAD

**Issue by blldd** [hackerchenzhuo/LaKo#7]
could you please upload the requirements.txt file, thanks.

when I run bash run_okvqa_train.sh, found this error:

(transformers==3.0.2)

Traceback (most recent call last):
File "train_reader.py", line 231, in
tokenizer = transformers.T5Tokenizer.from_pretrained(model_name, cache_dir=cache_dir)
File "/mnt/lustre/lidedong1/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1140, in from_pretrained
return cls._from_pretrained(*inputs, **kwargs)
File "/mnt/lustre/lidedong1/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1246, in _from_pretrained
list(cls.vocab_files_names.values()),
OSError: Model name 't5-base' was not found in tokenizers model name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). We assumed 't5-base' was a path, a model identifier, or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.

(transformers==4.10.0)

Traceback (most recent call last):
File "train_reader.py", line 281, in
tokenizer
File "train_reader.py", line 87, in train
dev_em = evaluate(model, eval_dataset, tokenizer, collator, opt, tk_tokenizer, pt_stemmer)
File "train_reader.py", line 145, in evaluate
max_length=50
File "/mnt/lustressd/lidedong1/workspace/MLP/projects/LaKo/src/model.py", line 60, in generate
max_length=max_length
File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/mnt/lustre/lidedong1/.local/lib/python3.6/site-packages/transformers/generation_utils.py", line 933, in generate
raise ValueError("Make sure that model_kwargs include encoder_outputs of type ModelOutput.")
ValueError: Make sure that model_kwargs include encoder_outputs of type ModelOutput.

Can you figure out why?

**Comment by hackerchenzhuo** [comment]
The requirements are in Readme:

- Python 3
- [PyTorch](http://pytorch.org/) (>= 1.6.0)
- [Transformers](http://huggingface.co/transformers/) (version 3.0.2)
- [NumPy](http://www.numpy.org/)
- faiss-cpu

**Comment by hackerchenzhuo** [comment]
Transformers's version should be version 3.0.2 or part of version 3.X.X.
It is not compatible with the latest version.
